### ISSUE TITLE
Storybook: Use Vite for Storybook build

### ISSUE THREAD

**Issue by daneah** [ithaka/pharos#110]
**The problem**
It can be slow to build Storybook from scratch, locally or on Netlify.

**The solution**
Storybook recently released [support for Vite](https://storybook.js.org/blog/storybook-for-vite/) which can significantly improve the speed of builds.

**Alternatives considered**
We've discussed only rebuilding the `@ithaka/pharos` code when necessary as one way of speeding up builds, which saw a non-trivial improvement in build time but may necessarily introduce additional complexity into the delivery process.

**Additional information**
Some Storybook addons still depend on Webpack per the blog post, so we should take care that the addons we're using continue to function properly.

There's one outstanding [issue](https://github.com/vitejs/vite/issues/2499) (with corresponding [pull request](https://github.com/vitejs/vite/pull/3627)) we may need to land before doing this.

**Comment by Niznikr** [comment]
Seems the linked issue is irrelevant and the error can be corrected by removing the `~` character from SASS imports in our example pages. The docs tab throws a JS error as well as our mdx intro and changelog pages, but the component stories load up fine.

**Comment by Niznikr** [comment]
The docs tab error seems related to this [issue](https://github.com/eirslett/storybook-builder-vite/issues/13).

**Comment by Niznikr** [comment]
Current issues:

- Missing [react-docgen-typescript equivalent](https://github.com/eirslett/storybook-builder-vite/issues/2)
- Dynamic imports not working in the built Storybook since [dynamic-import-vars](https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars) requires an extension at the end (which when added breaks dev Storybook as extensions between TS/JS for those get murky)
