### ISSUE TITLE
Chrome crashes on combination of pharos-input-group, pharos-heading, pharos-link

### ISSUE THREAD

**Issue by chrisjbrown** [ithaka/pharos#151]
**Expected behavior**
doesn't crash

**Actual behavior**
crashes

**Steps to reproduce the issue**

with an input box on the page
and a link inside a heading.
example
```
<pharos-input-group class="border" placeholder="bla" />
<pharos-heading level="1" preset="2">
    <pharos-link href="/google">
        bla bla bla
    </pharos-link>
</pharos-heading>
```
type something in the input box
then right click on the input box.
the tab crashes! (only in chrome)(firefox is fine :fox_face: and all other browsers)

link to [sandbox](https://m9st8.csb.app/)
link to [edit sandbox](https://codesandbox.io/s/icy-river-m9st8?file=/src/components/HelloWorld.vue)

**Screenshots or code**
If applicable, add screenshots or code to help explain the issue.

**Pharos version**
10.4

**Your environment**

- OS: macOS
- Browser: Chrome
- Version: 91

**Comment by daneah** [comment]
We were unable to reproduce this issue in Firefox, Safari, or even the Chromium-based version of Edge for macOS. This feels then like it could be a Chrome-specific bug—I enabled crash reporting and initiated the crash so that it will be reported directly to the Chrome folks.

We could in the meantime provide some kind of guidance—whether about this specifically, or generally about the preferred DOM ordering for linked headings that would avoid this issue.

**Comment by daneah** [comment]
@chrisjbrown I'm no longer able to reproduce this in Chrome 92. Can you confirm? I attempted to see if anything in [their git log](https://chromium.googlesource.com/chromium/src/+log/92.0.4515.115..92.0.4515.131?pretty=fuller&n=10000) was revealing, but didn't have a lot of luck.

**Comment by Niznikr** [comment]
Confirmed with @chrisjbrown that it has been fixed for the latest two versions.
