### ISSUE TITLE
Broken storybook

### ISSUE THREAD

**Issue by satya-achanta-venkata** [ithaka/pharos#287]
**Expected behavior**

All the elements stories should be displayed with proper styling.

**Actual behavior**

Some of the elements' stories have been broken, meaning we cannot see the expected behavior of the elements in the Storybook. This behavior might be due to #280 but this issue was not observed at that time.

**Steps to reproduce the issue**

1. Visit [Dropdown Menu Storybook](https://pharos.jstor.org/storybook/?path=/story/webcomponents_components-dropdown-menu--base)
2. You will find clicking on button doesn't display DropdownMenuItem

**Screenshots or code**

<img width="1655" alt="Screen Shot 2021-12-27 at 10 58 34 AM" src="https://user-images.githubusercontent.com/57365199/147488049-db998f46-2775-458e-9da0-cc052e74b06c.png">

**Pharos version**
11.2.1

**Your environment**

- OS: macOS
- Browser: Chrome
- Version:  96.0.4664.93

**Additional information**
Add any additional notes or further context about the issue here, including any known workarounds.

**Comment by daneah** [comment]
It appears that Storybook composition may be involved, because although the [web component story](https://pharos.jstor.org/storybook/?path=/story/webcomponents_components-button--base&args=variant:!undefined;type:!undefined) for a component in the composed Storybook is broken, the [composed React story](https://pharos.jstor.org/storybook/?path=/story/react_components-button--base&args=variant:!undefined;type:!undefined), [individual React story](https://pharos.jstor.org/storybooks/react/?path=/story/components-button--base) and [individual web component story](https://pharos.jstor.org/storybooks/wc/?path=/story/components-button--base) work fine.
