### ISSUE TITLE
Upgrade to Yarn berry / Yarn PnP

### ISSUE THREAD

**Issue by daneah** [ithaka/pharos#635]
**The problem**

We're currently on Yarn 1, and don't want to get too far behind. Recent versions of Yarn have [several benefits and features](https://yarnpkg.com/migration/overview) that are being used internally that would also benefit this project.

**The solution**

Upgrade to Yarn berry / Yarn PnP

**Additional information**

* Follow the migration guide for getting on Yarn berry
* Follow the "To go further" guide to get on Yarn PnP
* Update user scripts with `pre` and `post` to be run explicitly
* Fix missing and misconfigured dependencies based on build/process errors

I tried this briefly myself, and got just about through all the steps, before finally running into some TypeScript issues—this could be because of some additional missing/incorrect TypeScript configuration/dependencies.

**Comment by michael-iden** [comment]
@daneah I would like to contribute to this in the next few weeks if you also have availability. I don't feel I have the experience with the pharos setup to go it alone with confidence. Related, [I have a likely unmergable PR](https://github.com/ithaka/pharos/pull/650/files#diff-3fec3e7681402b1e4799321a89db6a2292e9ccd08609ab5150102e2c9aff9b47) because of issues running pharos where my global yarn is now 4.x

**Comment by daneah** [comment]
This, as written, was handled in #694—we may eventually want to try out Zero installs, but that's a different story!
